### ISSUE TITLE
[Comfy] Left bottom sidebar broken (shifted to the right)

### ISSUE THREAD

**Issue by pinetreemoonlight** [Metro420yt/Discord-comfy#1]
Hey, I found your fork of Comfy theme while searching for a fix for this. Since today, my bottom left sidebar looks like this: the settings etc. icons are shifted to the right. I narrowed the cause down to comfy theme. I tried updating classes (on my own fork), but it did not fix it. I am not very knowledgable of this stuff, so maybe you can have a look at it?

![image](https://github.com/user-attachments/assets/e1742fe0-dfcf-4482-b71e-7ba42676e9b3)

**Comment by Metro420yt** [comment]
sorry just seeing this, pushed a fix, not exactly sure what broke it though
you can check [this pr](https://github.com/Comfy-Themes/Discord/pull/162) to see the fix
